### ISSUE TITLE
Make a random resource.

### ISSUE THREAD

**Issue by paddycarver** [salaxander/terraform-provider-pokemon#1]
As seen in the [random provider](https://terraform.io/docs/providers/random) if you use a data source to obtain a random value, it will change on every Terraform refresh/plan/apply. This makes it hard to use when interpolating into other resources, as it can't be stable. By making it a resource that sets the value at creation time and is a no-op on read/destroy/update, the value can be stabilised and is then safe to interpolate into other resources without causing churn on every apply.

**Comment by salaxander** [comment]
Fixed by using the suggestions opened in #3 :)
