### ISSUE TITLE
Make all fields except "name" Computed, not Optional.

### ISSUE THREAD

**Issue by paddycarver** [salaxander/terraform-provider-pokemon#2]
Because all the fields except for "name" are Optional, values can be specified for them. These values won't be used, however. By setting them to "Computed", without "Optional" or "Required" set, you can disallow input and use them to surface API information.

Additionally, since "name" can be supplied from the provider, it should technically be set to "Optional" _and_ "Computed", as "Computed" signifies that the provider may return a value other than what is in the config for that field. (I mean, the real meaning is more complicated, but that's the gist of it in this case.)

**Comment by salaxander** [comment]
Fixed in recent push
